# Generated by Django 5.2.1 on 2025-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soinsinfirmier',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='numero_ordre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
