# Generated by Django 5.2.1 on 2025-06-05 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date_rdv', '-heure_rdv'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='heure_rdv',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_rdv',
            field=models.DateField(),
        ),
    ]
