# Generated by Django 5.2.1 on 2025-06-15 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_assurance_patient_medecin_traitant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='heure_rdv',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
