# Generated by Django 5.2.1 on 2025-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_planning_options_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='numero_licence',
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies connues'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='derniere_maj_profil',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour du profil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medicaments_actuels',
            field=models.TextField(blank=True, null=True, verbose_name='Médicaments actuels'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personne_urgence_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact d'urgence - Nom"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personne_urgence_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Contact d'urgence - Téléphone"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='poids',
            field=models.FloatField(blank=True, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profil_complete',
            field=models.BooleanField(default=False, verbose_name='Profil médical complété'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='taille',
            field=models.FloatField(blank=True, null=True, verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tension_diastolique',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tension diastolique'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tension_systolique',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tension systolique'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('docteur', 'Médecin'), ('admin', 'Administrateur'), ('infirmier', 'Infirmier'), ('secretaire', 'Secrétaire')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
